---

- name: Include aws_vpc provisioner tasks
  include_tasks: "{{ role_path }}/tasks/cloud_vpn/provisioners/aws_vpc/responder/provision.yaml"
  when: cloud_vpn_responder_manage_vpc

- name: Include aws_igw provisioner tasks
  include_tasks: "{{ role_path }}/tasks/cloud_vpn/provisioners/aws_igw/responder/provision.yaml"
  when: cloud_vpn_responder_manage_gw

- name: Include aws_instance provisioner tasks
  include_tasks: "{{ role_path }}/tasks/cloud_vpn/provisioners/aws_instance/responder/provision.yaml"
